stages:
  - lint
  - build
  - publish

variables:
  IMAGE_NAME: "entrypoint-scripts"
  IMAGE_VERSION: "0.0.1"

workflow:
  rules:
    # Avoid the pipeline to be triggered for merge request event, because it would be a duplicated event when
    #  a push is made on a branch that has an open merge request linked (as suggested in the default GitLab workflow)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never

lint-dockerfiles:
  stage: lint
  image: hadolint:latest-debian
  variables:
  #HADOLINT_OPT: --ignore DL3008
  script:
    - hadolint ${HADOLINT_OPT} Dockerfile

build-docker-image:
  stage: build
  image: docker:latest
  needs:
    - job: lint-dockerfiles
  script:
    - echo "Build command is \n\t docker build -t cytomine/${IMAGE_NAME}:${IMAGE_VERSION} -t cytomine/${IMAGE_NAME}:latest -f Dockerfile ."
    - docker build -t cytomine/${IMAGE_NAME}:${IMAGE_VERSION} -t cytomine/${IMAGE_NAME}:latest -f Dockerfile .