stages:
  - lint
  - build
  - publish

variables:
  IMAGE_NAME: "entrypoint-scripts"
  IMAGE_VERSION: "0.0.1"

workflow:
  rules:
    # Avoid the pipeline to be triggered for merge request event, because it would be a duplicated event when
    #  a push is made on a branch that has an open merge request linked (as suggested in the default GitLab workflow)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never

    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /^ce-.*$/
      variables:
        IS_OPEN_SOURCE_RELEASE_CANDIDATE: "true"
    - if: $CI_COMMIT_TAG == null || $CI_COMMIT_REF_NAME !~ /^ce-.*$/
      variables:
        IS_OPEN_SOURCE_RELEASE_CANDIDATE: "false"

    - when: always

default:
  tags:
    - docker

lint-dockerfiles:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  variables:
  #HADOLINT_OPT: --ignore DL3008
  script:
    - hadolint ${HADOLINT_OPT} Dockerfile
  rules:
    - changes:
        - Dockerfile
      when: always

    # If the Dockerfile has not been changed, this job can be skipped and manually invoked manually later
    - when: manual
      allow_failure: true

build-docker-image:
  stage: build
  image: docker:latest
  script:
    - echo "Build command is \n\t docker build -t cytomine/${IMAGE_NAME}:${IMAGE_VERSION} -t cytomine/${IMAGE_NAME}:latest -f Dockerfile ."
    - docker build -t cytomine/${IMAGE_NAME}:${IMAGE_VERSION} -t cytomine/${IMAGE_NAME}:latest -f Dockerfile .
    - |
      if [ $IS_OPEN_SOURCE_RELEASE_CANDIDATE = "true" ]; then
        echo "No tag has been pushed, this build will not be published to ${DOCKERHUB_URL}"
      else
        echo "The tag $CI_COMMIT_TAG has been pushed. Publish the image to ${DOCKERHUB_URL}" 
        echo "Login to registry ${DOCKERHUB_URL} with user ${DOCKERHUB_USER}"
        docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD} ${DOCKERHUB_URL}
        echo "Pushing image to registry, tagged as cytomine/${IMAGE_NAME}:${IMAGE_VERSION} and cytomine/${IMAGE_NAME}:latest"
        docker push cytomine/${IMAGE_NAME}:latest --all-tags
      fi